### ISSUE TITLE
Image from url

### ISSUE THREAD

**Issue by Kaos1337** [arcturial/telegrambot#1]
Hello,
thank you for you library, about the example with the image "photo: fs.createReadStream(__dirname + '/test.jpg')" how can I do to send an image from an url?
Thank you.

**Comment by arcturial** [comment]
I can suggest two ways of doing so:
1. First download the file to your local server and then send it as a stream

The sendPhoto call uploads a file to the Telegram servers and according to their [documentation](https://core.telegram.org/bots/api#sendphoto) it only supports file content or a file_id from an existing file on their servers.
1. Use the "sendMessage" call and just send the URL as text.

Most Telegram clients will render a URL to an image with the image itself, so unless you want to send just the image without the URL in the message...this should be a suited alternative.

**Comment by Kaos1337** [comment]
Yeah, downloading it first and then uploading as if it was in local since the begin. Thanks!

**Comment by callmephilip** [comment]
You can use [request](https://github.com/request/request) library to get a readable stream directly on the remote file

``` javascript
var request = require('request')
api.sendPhoto({ chat_id: 1, photo: request.get('http://cats.com/image.png') }, function (err, message) {
    if (err) throw err;
    console.log(message);
});
```
