### ISSUE TITLE
no message listener

### ISSUE THREAD

**Issue by qadir-genetech** [arcturial/telegrambot#10]
Does this library support the listener?

something like 

```
api.on('message',function (err, test) {
    if (err) throw err;
    console.log(test);
});
```

if a user sends a message to bot, then on('message') should called at node side.
So that bot can reply automatically upon this call back.

**Comment by arcturial** [comment]
It does not, it's meant to only be a wrapper to their API. It should be fairly trivial to implement a timer in the application code that can choose to utilize callbacks or polling.
